version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm test
      - sam build --template-file template.yaml --cached
      - aws cloudformation package --template-file template.yaml --output-template-file template-out.yaml --s3-bucket bao-anh-express-lambda-app

artifacts:
  files:
    - packaged.yaml
    - template.yaml
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*
