version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo "Zipping source code..."
      - zip -r function.zip node_modules lambda.js src package.json package-lock.json appspec.yml
  post_build:
    commands:
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name express-lambda-app --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
    - appspec.yml
