version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo "Zipping source code..."
      - zip -r function.zip lambda.js appspec.yml

artifacts:
  files:
    - function.zip
    - appspec.yml
