Transform: AWS::Serverless-2016-10-31
Description: Express API deployed on AWS Lambda behind Amazon API Gateway

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: express-lambda-app
      Handler: lambda.handler
      CodeUri: s3://bao-anh-express-lambda-app/002c7bb59a88447e3be86214a8a0b1a9.zip
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Description: Express application packaged for AWS Lambda
      Events:
        ApiGatewayProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiGatewayRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
