Transform: AWS::Serverless-2016-10-31
Description: Express API deployed on AWS Lambda behind Amazon API Gateway

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: express-lambda-app
      Handler: lambda.handler
      CodeUri: ./
      Description: Express application packaged for AWS Lambda
      Events:
        ApiGatewayProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiGatewayRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
